before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -y libreadline6-dev gcc-5 autoconf
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 20
language: c
compiler:
    - clang
    - gcc
script: rm configure Makefile;  autoreconf --install && ./configure && make && sudo make install
notifications:
  email:
    recipients:
      - jess.portnoy@kaltura.com
    on_success: change
    on_failure: always
